name: fitgenie
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.6
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  http: ^1.1.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_widget_from_html: ^0.14.6
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  animate_do: ^3.3.4
  simple_timer: ^2.0.0
  shared_preferences: ^2.2.3
  intl: ^0.17.0
  pedometer: ^4.0.1
  cloud_firestore: ^4.17.5
  permission_handler: ^11.3.1
  firebase_in_app_messaging: ^0.7.5+7




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
